name: .NET MAUI 

on:
  push:
    branches: [ master , redesign]
  pull_request:
    branches: [ master , redesign]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Install MAUI workload
      run: dotnet workload install maui
    - name: Build
      run: dotnet build -c Release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.5
      with:
        path: App/bin/Release/
